# -*- coding: utf-8 -*-
"""EXP024ah plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GKccyCuhmUrj55T6ZpZkmERnCwbOFXcW
"""

"""
EXP024: Visualization Generation for Quantum State Revivals Classification
Generates all figures needed for the paper including:
- Eigenvalue spectra on unit circle
- Probability distribution evolution heatmaps
- Fidelity evolution plots
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
import matplotlib.gridspec as gridspec
from fractions import Fraction
import warnings
warnings.filterwarnings('ignore')

# Set publication-quality plot parameters
plt.rcParams.update({
    'font.size': 12,
    'font.family': 'serif',
    'axes.labelsize': 12,
    'axes.titlesize': 14,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'legend.fontsize': 10,
    'figure.dpi': 150,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight'
})

# Custom colormap for probability heatmaps
colors = ['#440154', '#3b528b', '#21918c', '#5ec962', '#fde725']
revival_cmap = LinearSegmentedColormap.from_list('revival', colors, N=256)


def construct_U_k(k, rho, alpha, beta):
    """Construct the quantum walk operator U_k on a cycle of k nodes."""
    C = np.array([
        [np.sqrt(rho), np.sqrt(1-rho) * np.exp(1j * alpha)],
        [np.sqrt(1-rho) * np.exp(1j * beta), -np.sqrt(rho) * np.exp(1j * (alpha + beta))]
    ], dtype=complex)

    U = np.zeros((2*k, 2*k), dtype=complex)

    for i in range(k):
        for s in [0, 1]:
            if s == 0:
                new_i = (i - 1) % k
            else:
                new_i = (i + 1) % k

            old_idx = i * 2 + s
            new_idx = new_i * 2 + s
            U[new_idx, old_idx] = 1.0

    I_k = np.eye(k)
    I_kron_C = np.kron(I_k, C)
    U = U @ I_kron_C

    return U


def simulate_walk(k, rho, delta, max_steps, initial_state=None):
    """
    Simulate quantum walk and return state vectors at each step.

    Parameters:
    - k: cycle length
    - rho: coin parameter
    - delta: phase sum (alpha+delta), with alpha=delta, beta=0
    - max_steps: number of steps to simulate
    - initial_state: initial state vector (default: |0, up>)

    Returns:
    - states: list of state vectors at each step
    - probabilities: list of probability distributions
    """
    U = construct_U_k(k, rho, delta, 0)

    if initial_state is None:
        psi = np.zeros(2*k, dtype=complex)
        psi[0] = 1.0  # |0, up>
    else:
        psi = initial_state

    states = [psi.copy()]
    probabilities = []

    for step in range(max_steps + 1):
        prob = np.abs(psi.reshape(k, 2))**2
        probabilities.append(prob)
        if step < max_steps:
            psi = U @ psi
            states.append(psi.copy())

    return states, np.array(probabilities)


def plot_eigenvalues(k, rho, delta, N, save_path=None):
    """
    Plot eigenvalues on the unit circle.

    Parameters:
    - k: cycle length
    - rho: coin parameter
    - delta: phase sum
    - N: revival period (for verification) - can be None for no revival
    - save_path: path to save the figure
    """
    U = construct_U_k(k, rho, delta, 0)
    eigenvalues = np.linalg.eigvals(U)

    # Sort eigenvalues by angle for better visualization
    angles = np.angle(eigenvalues)
    sort_idx = np.argsort(angles)
    eigenvalues = eigenvalues[sort_idx]

    fig, ax = plt.subplots(figsize=(8, 8))

    # Draw unit circle
    theta = np.linspace(0, 2*np.pi, 500)
    ax.plot(np.cos(theta), np.sin(theta), 'k-', alpha=0.3, linewidth=1)

    # Plot eigenvalues
    ax.plot(np.real(eigenvalues), np.imag(eigenvalues), 'o',
            color='#d73027', markersize=10, markeredgecolor='black',
            markeredgewidth=0.5, zorder=5)

    # Mark roots of unity for comparison (only if N is not None and N is reasonable)
    if N is not None and N <= 120:
        roots = np.exp(2j * np.pi * np.arange(N) / N)
        ax.plot(np.real(roots), np.imag(roots), '.', color='gray',
                alpha=0.2, markersize=2, zorder=1)

    # Formatting
    ax.set_aspect('equal')
    ax.set_xlim(-1.1, 1.1)
    ax.set_ylim(-1.1, 1.1)
    ax.axhline(y=0, color='k', linewidth=0.5, alpha=0.3)
    ax.axvline(x=0, color='k', linewidth=0.5, alpha=0.3)
    ax.set_xlabel('Re($\\lambda$)', fontsize=12)
    ax.set_ylabel('Im($\\lambda$)', fontsize=12)

    # Title with parameters
    rho_str = f"{rho:.4f}" if isinstance(rho, float) else f"{rho}"
    title = f"$k={k}$, $\\rho={rho_str}$, $\\delta={delta/np.pi:.2f}\\pi$"
    if N is not None:
        title += f"\n{len(eigenvalues)} eigenvalues"
        if N:
            title += f", all ${N}$th roots of unity"
    else:
        title += f"\n{len(eigenvalues)} eigenvalues"
    ax.set_title(title, fontsize=12)

    ax.grid(True, alpha=0.2, linestyle='--')

    if save_path is None:
        rho_str = f"{rho:.4f}".replace('.', '_')
        save_path = f"eigenvalues_k{k}_rho{rho_str}_delta{delta:.3f}.png"
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"  Saved: {save_path}")


def plot_probability_heatmap(k, rho, delta, max_steps, N=None, save_path=None):
    """
    Create a heatmap of probability distribution evolution.

    Parameters:
    - k: cycle length
    - rho: coin parameter
    - delta: phase sum
    - max_steps: maximum steps to show
    - N: revival period (to mark with lines) - can be None
    - save_path: path to save the figure
    """
    states, probs = simulate_walk(k, rho, delta, max_steps)

    # Reshape probabilities for heatmap: (steps, positions)
    # Sum over spin states to get total position probability
    pos_probs = probs.sum(axis=2)  # (steps, k)

    fig, ax = plt.subplots(figsize=(12, 8))

    # Create heatmap
    im = ax.imshow(pos_probs.T, aspect='auto', origin='lower',
                   cmap=revival_cmap, interpolation='bilinear',
                   extent=[0, max_steps, -0.5, k-0.5])

    # Mark revival steps (only if N is provided and within range)
    if N is not None and N <= max_steps:
        ax.axvline(x=N, color='white', linestyle='--', linewidth=2,
                   alpha=0.8, label=f'Revival at N={N}')

    # Formatting
    ax.set_xlabel('Step Number', fontsize=12)
    ax.set_ylabel('Position', fontsize=12)

    rho_str = f"{rho:.4f}" if isinstance(rho, float) else f"{rho}"
    ax.set_title(f'Probability Distribution Evolution\n$k={k}$, $\\rho={rho_str}$, $\\delta={delta/np.pi:.2f}\\pi$',
                 fontsize=12)
    ax.set_yticks(range(k))
    ax.set_yticklabels(range(k))

    # Colorbar
    cbar = plt.colorbar(im, ax=ax)
    cbar.set_label('Probability', fontsize=10)

    if N is not None and N <= max_steps:
        ax.legend(loc='upper right')

    plt.tight_layout()

    if save_path is None:
        rho_str = f"{rho:.4f}".replace('.', '_')
        save_path = f"probability_evolution_k{k}_rho{rho_str}_delta{delta:.3f}.png"
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"  Saved: {save_path}")


def plot_fidelity(k, rho, delta, max_steps, N=None, save_path=None):
    """
    Plot fidelity evolution over time.

    Parameters:
    - k: cycle length
    - rho: coin parameter
    - delta: phase sum
    - max_steps: maximum steps to simulate
    - N: revival period (to mark with lines) - can be None
    - save_path: path to save the figure
    """
    states, probs = simulate_walk(k, rho, delta, max_steps)

    # Initial state is |0, up>
    initial_state = np.zeros(2*k, dtype=complex)
    initial_state[0] = 1.0

    # Compute fidelity at each step
    fidelity = []
    for state in states:
        f = np.abs(np.vdot(initial_state, state))**2
        fidelity.append(f)

    fig, ax = plt.subplots(figsize=(10, 6))

    steps = np.arange(len(fidelity))
    ax.plot(steps, fidelity, 'b-', linewidth=1.5, label='Fidelity')

    # Mark revival steps (only if N is provided and within range)
    if N is not None and N <= max_steps:
        ax.axvline(x=N, color='red', linestyle='--', linewidth=2,
                   alpha=0.7, label=f'Revival at N={N}')
        if N < len(fidelity):
            ax.plot(N, fidelity[N], 'ro', markersize=8)

    # Mark fidelity=1 line
    ax.axhline(y=1, color='k', linestyle=':', linewidth=1, alpha=0.5, label='Perfect revival')

    ax.set_xlabel('Step Number', fontsize=12)
    ax.set_ylabel('Fidelity $F(t) = |\\langle\\psi_0|\\psi_t\\rangle|^2$', fontsize=12)

    rho_str = f"{rho:.4f}" if isinstance(rho, float) else f"{rho}"
    ax.set_title(f'Fidelity Evolution\n$k={k}$, $\\rho={rho_str}$, $\\delta={delta/np.pi:.2f}\\pi$',
                 fontsize=12)

    ax.set_ylim(-0.05, 1.05)
    ax.grid(True, alpha=0.3)
    ax.legend(loc='upper right')

    plt.tight_layout()

    if save_path is None:
        rho_str = f"{rho:.4f}".replace('.', '_')
        save_path = f"fidelity_k{k}_rho{rho_str}_delta{delta:.3f}.png"
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"  Saved: {save_path}")


def plot_comparative_fidelity(k_values, rho_values, delta_values, N_values, max_steps, save_path=None):
    """
    Plot multiple fidelity curves for comparison.
    """
    fig, ax = plt.subplots(figsize=(12, 6))

    colors_list = ['#1b9e77', '#d95f02', '#7570b3', '#e7298a', '#66a61e', '#e6ab02']

    for idx, (k, rho, delta, N) in enumerate(zip(k_values, rho_values, delta_values, N_values)):
        states, probs = simulate_walk(k, rho, delta, max_steps)

        initial_state = np.zeros(2*k, dtype=complex)
        initial_state[0] = 1.0

        fidelity = [np.abs(np.vdot(initial_state, state))**2 for state in states]

        label = f"k={k}, ρ={rho:.3f}, δ={delta/np.pi:.2f}π, N={N}"
        ax.plot(fidelity, color=colors_list[idx % len(colors_list)],
                linewidth=1.5, label=label, alpha=0.8)

    ax.set_xlabel('Step Number', fontsize=12)
    ax.set_ylabel('Fidelity', fontsize=12)
    ax.set_title('Comparative Fidelity Evolution for Revival Cases', fontsize=14)
    ax.set_ylim(-0.05, 1.05)
    ax.grid(True, alpha=0.3)
    ax.legend(loc='upper right', fontsize=9)

    plt.tight_layout()

    if save_path is None:
        save_path = "comparative_fidelity.png"
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"  Saved: {save_path}")


def plot_classification_summary(save_path=None):
    """
    Create a summary figure showing the complete classification.
    """
    fig, ax = plt.subplots(figsize=(14, 8))

    # Define revival and non-revival k values
    revival_ks = [2, 3, 4, 5, 6, 8, 10]
    no_revival_ks = list(range(1, 31))
    no_revival_ks = [k for k in no_revival_ks if k not in revival_ks and k != 1]

    # Color coding
    revival_color = '#2ca25f'
    no_revival_color = '#de2d26'

    # Plot revival cases
    y = np.ones(len(revival_ks))
    ax.bar(revival_ks, y, width=0.8, color=revival_color, alpha=0.7,
           edgecolor='black', linewidth=0.5, label='Revival exists')

    # Plot non-revival cases
    y = np.ones(len(no_revival_ks))
    ax.bar(no_revival_ks, y, width=0.8, color=no_revival_color, alpha=0.3,
           edgecolor='gray', linewidth=0.5, label='No revival')

    # Add value labels on bars
    for k in revival_ks:
        ax.text(k, 0.5, str(k), ha='center', va='center', fontsize=10,
                color='white', fontweight='bold')

    ax.set_xlabel('Cycle Length k', fontsize=12)
    ax.set_ylabel('Revival Status', fontsize=12)
    ax.set_title('Complete Classification of Quantum State Revivals\n'
                 'Nontrivial revivals exist only for k = 2, 3, 4, 5, 6, 8, 10',
                 fontsize=14)
    ax.set_xlim(0.5, 30.5)
    ax.set_ylim(0, 1.5)
    ax.set_yticks([])
    ax.legend(loc='upper right', fontsize=10)

    # Add annotation boxes for special cases
    ax.annotate('Doubling:\n3->6, 5->10', xy=(4, 1.2), xytext=(8, 1.2),
                arrowprops=dict(arrowstyle='->', color='gray', lw=1),
                fontsize=9, ha='center')

    ax.annotate('Special:\n2, 4, 8', xy=(2, 1.2), xytext=(2, 1.3),
                fontsize=9, ha='center')

    ax.annotate('No revivals\nfor k>=7 except 8,10', xy=(15, 1.2), xytext=(20, 1.2),
                fontsize=9, ha='center')

    plt.tight_layout()

    if save_path is None:
        save_path = "classification_summary.png"
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"  Saved: {save_path}")


def plot_decision_tree(save_path=None):
    """
    Create a text-based decision tree visualization.
    """
    fig, ax = plt.subplots(figsize=(12, 8))
    ax.axis('off')

    tree_text = r"""
    +---------------------------------------------------------------------------------+
    |                    START: Cycle length k                                        |
    +---------------------------------------------------------------------------------+
                                    |
                                    v
                    +-------------------------------+
                    |  Is k in {2,3,4,5,6,8,10}?    |
                    +-------------------------------+
                           |                    |
                    YES    |                    |    NO
                           v                    v
        +--------------------------+    +--------------------------+
        |   REVIVALS EXIST         |    |   NO REVIVALS            |
        |   0 < rho < 1            |    |   Only rho = 0, 1        |
        +--------------------------+    +--------------------------+
                           |
                           v
        +---------------------------------------------------------------------------------+
        |  DETAILS:                                                                       |
        |  * k=2: any rho, delta=0, N=2                                                  |
        |  * k=3: Many values (Dukes Table 3)                                            |
        |  * k=4: Many values (Dukes Table 4)                                            |
        |  * k=5: rho = (5 +/- sqrt(5))/10, delta = 2*pi*p/5, N=60                      |
        |  * k=6: Same as k=3 (inherited)                                                |
        |  * k=8: rho = 1/2, delta = 0, pi/2, pi, 3*pi/2, N=24                          |
        |  * k=10: Same as k=5 (inherited)                                               |
        +---------------------------------------------------------------------------------+
    """

    ax.text(0.5, 0.5, tree_text, transform=ax.transAxes,
            fontsize=9, verticalalignment='center', horizontalalignment='center',
            family='monospace')

    ax.set_title('Decision Tree for Quantum State Revivals', fontsize=14, pad=20)

    plt.tight_layout()

    if save_path is None:
        save_path = "decision_tree.png"
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"  Saved: {save_path}")


def plot_k4_phase_diagram(save_path=None):
    """
    Create a phase diagram showing revival regions for k=4.
    """
    fig, ax = plt.subplots(figsize=(10, 8))

    # Known revival points from Dukes Table 4
    revival_points = [
        (0.5, 0), (0.5, np.pi), (0.5, np.pi/2), (0.5, 3*np.pi/2),
        (0.75, 0), (0.75, np.pi),
        (0.25, 0), (0.25, np.pi),
        ((2 - np.sqrt(3))/2, np.pi/2), ((2 - np.sqrt(3))/2, 3*np.pi/2),
    ]

    # Plot all revival points
    for rho, delta in revival_points:
        ax.plot(rho, delta/np.pi, 'ro', markersize=10, markeredgecolor='black',
                markeredgewidth=1)

    # Add labels for key points
    ax.annotate('N=8', xy=(0.5, 0), xytext=(0.55, 0.1), fontsize=9)
    ax.annotate('N=6', xy=(0.75, 0), xytext=(0.8, 0.1), fontsize=9)
    ax.annotate('N=12', xy=(0.25, 0), xytext=(0.3, 0.1), fontsize=9)
    ax.annotate('N=12', xy=(0.13397, 0.5), xytext=(0.05, 0.6), fontsize=9)

    ax.set_xlabel('rho', fontsize=12)
    ax.set_ylabel('delta / pi', fontsize=12)
    ax.set_title('k=4 Revival Parameter Space\nKnown revival points (from Dukes Table 4)',
                 fontsize=12)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 2)
    ax.grid(True, alpha=0.3)

    ax.legend(['Known revival points'], loc='upper right', fontsize=10)

    plt.tight_layout()

    if save_path is None:
        save_path = "k4_phase_diagram.png"
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"  Saved: {save_path}")


def generate_all_figures():
    """
    Generate all figures needed for the paper.
    """
    print("Generating figures for EXP024...")
    print("=" * 60)

    # Figure 1: Classification summary
    print("\n1. Generating classification summary...")
    plot_classification_summary("classification_summary.png")
    plot_decision_tree("decision_tree.png")

    # Figure 2: Eigenvalue spectra
    print("\n2. Generating eigenvalue spectra...")

    # k=4 revival case
    plot_eigenvalues(k=4, rho=0.5, delta=0, N=8,
                     save_path="eigenvalues_k4_rho05_delta0.png")

    # k=5 revival case
    rho_k5 = (5 - np.sqrt(5)) / 10
    plot_eigenvalues(k=5, rho=rho_k5, delta=0, N=60,
                     save_path="eigenvalues_k5_rho0276_delta0.png")

    # k=8 revival case
    plot_eigenvalues(k=8, rho=0.5, delta=0, N=24,
                     save_path="eigenvalues_k8_rho05_delta0.png")

    # k=12 no-revival case (for comparison)
    plot_eigenvalues(k=12, rho=0.5, delta=0, N=None,
                     save_path="eigenvalues_k12_rho05_delta0_norevival.png")

    # Figure 3: Probability distribution evolution
    print("\n3. Generating probability distribution heatmaps...")

    # k=4 revival: ρ=0.5, δ=0, N=8
    plot_probability_heatmap(k=4, rho=0.5, delta=0, max_steps=20, N=8,
                              save_path="probability_evolution_k4_rho05_delta0.png")

    # k=4 non-revival: ρ=0.8, δ=0 (periodic but not revival)
    plot_probability_heatmap(k=4, rho=0.8, delta=0, max_steps=20, N=None,
                              save_path="probability_evolution_k4_rho08_delta0.png")

    # k=5 revival case
    plot_probability_heatmap(k=5, rho=rho_k5, delta=0, max_steps=70, N=60,
                              save_path="probability_evolution_k5_rho0276_delta0.png")

    # k=8 revival case
    plot_probability_heatmap(k=8, rho=0.5, delta=0, max_steps=30, N=24,
                              save_path="probability_evolution_k8_rho05_delta0.png")

    # Figure 4: Fidelity evolution
    print("\n4. Generating fidelity evolution plots...")

    # k=4 revival
    plot_fidelity(k=4, rho=0.5, delta=0, max_steps=20, N=8,
                  save_path="fidelity_k4_rho05_delta0.png")

    # k=5 revival
    plot_fidelity(k=5, rho=rho_k5, delta=0, max_steps=70, N=60,
                  save_path="fidelity_k5_rho0276_delta0.png")

    # k=8 revival
    plot_fidelity(k=8, rho=0.5, delta=0, max_steps=30, N=24,
                  save_path="fidelity_k8_rho05_delta0.png")

    # k=12 no revival
    plot_fidelity(k=12, rho=0.5, delta=0, max_steps=50, N=None,
                  save_path="fidelity_k12_rho05_delta0_norevival.png")

    # Figure 5: Comparative fidelity
    print("\n5. Generating comparative fidelity plot...")

    k_values = [3, 4, 5, 6, 8, 10]
    rho_values = [
        2/3,
        0.5,
        (5 - np.sqrt(5))/10,
        2/3,
        0.5,
        (5 - np.sqrt(5))/10
    ]
    delta_values = [0, 0, 0, 0, 0, 0]
    N_values = [8, 8, 60, 8, 24, 60]

    plot_comparative_fidelity(k_values, rho_values, delta_values, N_values, max_steps=70,
                               save_path="comparative_fidelity.png")

    # Additional: Phase space diagram for k=4
    print("\n6. Generating k=4 phase space diagram...")
    plot_k4_phase_diagram("k4_phase_diagram.png")

    print("\n" + "=" * 60)
    print("All figures generated successfully!")
    print("=" * 60)


if __name__ == "__main__":
    generate_all_figures()

    print("\n" + "=" * 60)
    print("FILE SUMMARY:")
    print("=" * 60)
    print("""
    Generated files:

    Classification:
    - classification_summary.png
    - decision_tree.png

    Eigenvalue spectra:
    - eigenvalues_k4_rho05_delta0.png
    - eigenvalues_k5_rho0276_delta0.png
    - eigenvalues_k8_rho05_delta0.png
    - eigenvalues_k12_rho05_delta0_norevival.png

    Probability evolution:
    - probability_evolution_k4_rho05_delta0.png
    - probability_evolution_k4_rho08_delta0.png
    - probability_evolution_k5_rho0276_delta0.png
    - probability_evolution_k8_rho05_delta0.png

    Fidelity evolution:
    - fidelity_k4_rho05_delta0.png
    - fidelity_k5_rho0276_delta0.png
    - fidelity_k8_rho05_delta0.png
    - fidelity_k12_rho05_delta0_norevival.png

    Comparative analysis:
    - comparative_fidelity.png
    - k4_phase_diagram.png
    """)