# -*- coding: utf-8 -*-
"""EXP024ab k5 search - verified but nothing new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18UWV5oK8taPUojS7APA2LDoHKbAKjl1f
"""

import numpy as np
from fractions import Fraction
from itertools import combinations
import warnings
warnings.filterwarnings('ignore')

def construct_U_k(k, rho, alpha, beta):
    """
    Construct the quantum walk operator U_k on a cycle of k nodes.
    """
    # Coin operator (2x2 unitary)
    C = np.array([
        [np.sqrt(rho), np.sqrt(1-rho) * np.exp(1j * alpha)],
        [np.sqrt(1-rho) * np.exp(1j * beta), -np.sqrt(rho) * np.exp(1j * (alpha + beta))]
    ], dtype=complex)

    # Initialize U_k as 2k x 2k zero matrix
    U = np.zeros((2*k, 2*k), dtype=complex)

    # Construct conditional shift operator S_k
    for i in range(k):
        for s in [0, 1]:  # 0=up, 1=down
            if s == 0:  # spin up goes left
                new_i = (i - 1) % k
            else:  # spin down goes right
                new_i = (i + 1) % k

            old_idx = i * 2 + s
            new_idx = new_i * 2 + s
            U[new_idx, old_idx] = 1.0

    # Apply coin operator: U = S * (I_k ⊗ C)
    I_k = np.eye(k)
    I_kron_C = np.kron(I_k, C)
    U = U @ I_kron_C

    return U

def verify_revival(k, rho, delta, N, tol=1e-8):
    """
    Verify that U_k^N = I_{2k} for given parameters.
    """
    alpha = delta
    beta = 0.0

    U = construct_U_k(k, rho, alpha, beta)

    # Compute U^N using repeated squaring for better numerical stability
    U_power = np.linalg.matrix_power(U, N)

    # Check if U^N is approximately identity
    I = np.eye(2*k, dtype=complex)
    diff = np.linalg.norm(U_power - I)

    # Compute eigenvalues
    eigenvalues = np.linalg.eigvals(U)
    eigvals_are_roots = True
    max_eig_error = 0
    for ev in eigenvalues:
        error = abs(ev**N - 1)
        max_eig_error = max(max_eig_error, error)
        if error > tol:
            eigvals_are_roots = False

    return {
        'diff_norm': diff,
        'is_identity': diff < tol,
        'eigenvalues_are_Nth_roots': eigvals_are_roots,
        'max_eig_error': max_eig_error
    }

def verify_dukes_k5_solutions():
    """
    Verify the known k=5 solutions from Dukes' Table 5.
    """
    print("\n" + "=" * 80)
    print("VERIFYING DUKES' k=5 SOLUTIONS FROM TABLE 5")
    print("=" * 80)

    # From Table 5: k=5,10 with N=60
    # ρ = (5 ± √5)/10
    rho1 = (5 - np.sqrt(5)) / 10
    rho2 = (5 + np.sqrt(5)) / 10

    # δ values from the paper: 0, 2π/5, 4π/5, 6π/5, 8π/5
    delta_values = [0, 2*np.pi/5, 4*np.pi/5, 6*np.pi/5, 8*np.pi/5]

    solutions_found = []

    for rho in [rho1, rho2]:
        for delta in delta_values:
            result = verify_revival(5, rho, delta, 60, tol=1e-8)

            if result['is_identity']:
                solutions_found.append((rho, delta, result))
                status = "✓ PASS"
            else:
                status = "✗ FAIL"

            print(f"ρ = {rho:.10f}, δ = {delta:.4f} rad ({np.degrees(delta):.0f}°): {status}")
            print(f"    ||U^60 - I|| = {result['diff_norm']:.2e}")
            print(f"    Max |λ^60 - 1| = {result['max_eig_error']:.2e}")

    return solutions_found

def search_k5_revivals(max_N=120, max_denom=20, verbose=True):
    """
    Search for k=5 revival solutions.

    For k=5, from Eq. (86-87) in paper, when δ = 2π·p/5:
    ρ' = (4/(5+√5)) * (1 - cos(4π m'/n' - δ))
    ρ'' = (4/(5-√5)) * (1 - cos(4π m''/n'' - δ))

    Need ρ' = ρ'' and 0 < ρ < 1.
    """

    print("\n" + "=" * 80)
    print(f"SEARCHING FOR NEW k=5 REVIVALS (max_N={max_N}, max_denom={max_denom})")
    print("=" * 80)

    # Known δ values from Dukes that reduce the problem
    # For k=5, δ = 2π·p/5 (p=0,1,2,3,4) are special
    delta_values = []
    for p in range(5):
        delta = 2 * np.pi * p / 5
        # Skip p=0? No, include all
        delta_values.append((delta, f"2π·{p}/5"))

    # Also try other δ values that might work
    for q in range(3, 13):
        for p in range(1, q):
            if np.gcd(p, q) == 1:
                delta = 2 * np.pi * p / q
                # Skip if too close to multiples of 2π/5
                skip = False
                for known in [0, 2*np.pi/5, 4*np.pi/5, 6*np.pi/5, 8*np.pi/5]:
                    if abs(delta - known) < 0.01:
                        skip = True
                        break
                if not skip:
                    delta_values.append((delta, f"2π·{p}/{q}"))

    print(f"Testing {len(delta_values)} δ values...")

    # Generate rational fractions for 4π m/n
    fractions = []
    for denom in range(1, max_denom + 1):
        for num in range(1, denom):
            if np.gcd(num, denom) == 1:
                # θ = 4π * m/n
                fractions.append((num, denom, 4 * np.pi * num / denom))

    print(f"Testing {len(fractions)} rational fractions for ρ' and ρ''...")

    new_solutions = []
    tested_pairs = 0

    # Constants for k=5
    sqrt5 = np.sqrt(5)
    coeff1 = 4 / (5 + sqrt5)  # ~0.5528
    coeff2 = 4 / (5 - sqrt5)  # ~1.4472 (but ρ must be ≤1, so this will limit)

    for delta, delta_name in delta_values:
        cos_delta = np.cos(delta)

        # For each δ, search for matching ρ' and ρ''
        for (m1, n1, theta1) in fractions:
            for (m2, n2, theta2) in fractions:
                tested_pairs += 1

                # Skip if same fraction
                if m1 == m2 and n1 == n2:
                    continue

                # Compute candidate ρ from first fraction
                A = 1 - np.cos(theta1 - delta)
                rho_prime = coeff1 * A

                # Compute candidate ρ from second fraction
                B = 1 - np.cos(theta2 - delta)
                rho_double_prime = coeff2 * B

                # Check if they match and are in valid range
                if abs(rho_prime - rho_double_prime) < 1e-6 and 0 < rho_prime < 1:
                    rho = rho_prime

                    # Determine N from denominators
                    # Need to consider the gcd structure
                    N_candidates = []

                    # For l=0 block: eigenvalues involve e^{±iδ/2}
                    delta_frac = Fraction(delta / (2 * np.pi)).limit_denominator(max_denom * 2)
                    n_delta = delta_frac.denominator

                    # Also need the fractions from the successful match
                    N = np.lcm.reduce([n1, n2, n_delta * 2])

                    if N <= max_N:
                        # Verify the full U_5^N = I
                        result = verify_revival(5, rho, delta, N, tol=1e-8)

                        if result['is_identity'] and result['eigenvalues_are_Nth_roots']:
                            solution = {
                                'N': N,
                                'rho': rho,
                                'delta': delta,
                                'delta_deg': np.degrees(delta),
                                'delta_name': delta_name,
                                'm1_n1': f"{m1}/{n1}",
                                'm2_n2': f"{m2}/{n2}",
                                'diff': result['diff_norm']
                            }

                            # Check if this is one of Dukes' known solutions
                            known_rhos = [(5 - np.sqrt(5))/10, (5 + np.sqrt(5))/10]
                            is_known = False
                            for known_rho in known_rhos:
                                if abs(rho - known_rho) < 1e-8:
                                    is_known = True
                                    break

                            if not is_known:
                                new_solutions.append(solution)
                                if verbose:
                                    print(f"\n✨ POTENTIAL NEW k=5 SOLUTION!")
                                    print(f"   N = {N}")
                                    print(f"   ρ = {rho:.10f}")
                                    print(f"   δ = {delta:.6f} rad = {np.degrees(delta):.2f}° ({delta_name})")
                                    print(f"   Fractions: {m1}/{n1}, {m2}/{n2}")
                                    print(f"   ||U^{N} - I|| = {result['diff_norm']:.2e}")
                                    print(f"   Max |λ^N - 1| = {result['max_eig_error']:.2e}")
                            else:
                                if verbose and rho == known_rhos[0]:
                                    print(f"\n✓ Known Dukes solution confirmed for δ={delta_name}")

                # Progress update
                if tested_pairs % 5000 == 0 and verbose:
                    print(f"   Searched {tested_pairs} pairs, found {len(new_solutions)} new candidates...")

    return new_solutions

def analyze_k5_eigenvalue_structure():
    """
    Analyze the eigenvalue condition for k=5 more deeply.

    For k=5, the eigenvalues come in pairs from l=0,...,4.
    The condition for revival is that ALL eigenvalues are N-th roots of unity.
    """

    print("\n" + "=" * 80)
    print("ANALYZING k=5 EIGENVALUE STRUCTURE")
    print("=" * 80)

    from sympy import symbols, sqrt, cos, pi, exp, I, simplify, ratsimp

    # Symbolic analysis
    rho_sym, delta_sym = symbols('rho delta', real=True)

    print("\nTheoretical constraints for k=5:")
    print("-" * 50)
    print("For k=5, we need ρ_l equal for l=0,1,2,3,4")
    print("This gives 4 independent equations")
    print("The paper shows that choosing δ = 2π·p/5 reduces to 2 independent ρ forms")
    print("These are:")
    print("  ρ' = (4/(5+√5)) * (1 - cos(4π m'/n' - δ))")
    print("  ρ'' = (4/(5-√5)) * (1 - cos(4π m''/n'' - δ))")
    print("\nFor revival, we need ρ' = ρ'' AND both rational combinations")
    print("of 4π m/n must align with the eigenvalue phases.")

    return

def search_higher_N_k5():
    """
    Search for k=5 solutions with larger N (up to 240).
    """

    print("\n" + "=" * 80)
    print("SEARCHING FOR HIGHER-N k=5 REVIVALS (N ≤ 240)")
    print("=" * 80)

    # Focus on the special δ values from Dukes
    delta_values = [0, 2*np.pi/5, 4*np.pi/5, 6*np.pi/5, 8*np.pi/5]

    # For each δ, we need to solve ρ' = ρ''
    sqrt5 = np.sqrt(5)
    coeff1 = 4 / (5 + sqrt5)
    coeff2 = 4 / (5 - sqrt5)

    # Try larger denominators
    solutions = []

    for delta in delta_values:
        print(f"\nSearching δ = {np.degrees(delta):.0f}°...")

        # Try denominators up to 30
        for denom1 in range(1, 31):
            for num1 in range(1, denom1):
                if np.gcd(num1, denom1) != 1:
                    continue

                theta1 = 4 * np.pi * num1 / denom1
                A = 1 - np.cos(theta1 - delta)
                rho_prime = coeff1 * A

                if rho_prime <= 0 or rho_prime >= 1:
                    continue

                # Now find matching fraction for ρ''
                target_B = rho_prime / coeff2

                for denom2 in range(1, 31):
                    for num2 in range(1, denom2):
                        if np.gcd(num2, denom2) != 1:
                            continue

                        theta2 = 4 * np.pi * num2 / denom2
                        B = 1 - np.cos(theta2 - delta)

                        if abs(B - target_B) < 1e-8:
                            # Found match
                            N_candidate = np.lcm.reduce([denom1, denom2, 10])  # 10 from δ/2 for k=5

                            if N_candidate <= 240:
                                # Verify
                                result = verify_revival(5, rho_prime, delta, N_candidate)

                                if result['is_identity']:
                                    solution = {
                                        'N': N_candidate,
                                        'rho': rho_prime,
                                        'delta': delta,
                                        'm1_n1': f"{num1}/{denom1}",
                                        'm2_n2': f"{num2}/{denom2}"
                                    }

                                    # Check if new (not Dukes')
                                    is_dukes = abs(rho_prime - (5 - sqrt5)/10) < 1e-8 or \
                                               abs(rho_prime - (5 + sqrt5)/10) < 1e-8

                                    if not is_dukes:
                                        solutions.append(solution)
                                        print(f"\n  ✨ NEW: N={N_candidate}, ρ={rho_prime:.10f}")
                                        print(f"     Fractions: {num1}/{denom1}, {num2}/{denom2}")
                                    else:
                                        print(f"  ✓ Dukes: N={N_candidate}, ρ={rho_prime:.10f}")

    return solutions

# Main execution
if __name__ == "__main__":
    print("\n🔍 " * 30)
    print("SEARCHING FOR k=5 QUANTUM STATE REVIVALS")
    print("🔍 " * 30)

    # Verify Dukes' known solutions
    known_solutions = verify_dukes_k5_solutions()

    # Analyze the structure
    analyze_k5_eigenvalue_structure()

    # Search for new solutions with moderate N
    print("\n" + "🎯 " * 20)
    print("PHASE 1: SEARCHING FOR NEW SOLUTIONS (N ≤ 120)")
    print("🎯 " * 20)

    new_solutions = search_k5_revivals(max_N=120, max_denom=20, verbose=True)

    # Search for higher N solutions
    print("\n" + "🎯 " * 20)
    print("PHASE 2: SEARCHING FOR HIGHER-N SOLUTIONS (N ≤ 240)")
    print("🎯 " * 20)

    higher_solutions = search_higher_N_k5()

    # Summary
    print("\n" + "=" * 80)
    print("FINAL SUMMARY")
    print("=" * 80)

    print(f"\n✓ Dukes' known solutions: 2 ρ values × 5 δ values = 10 verified solutions")
    print(f"  All with N=60")

    if new_solutions:
        print(f"\n✨ POTENTIAL NEW SOLUTIONS FOUND: {len(new_solutions)}")
        for sol in new_solutions[:10]:  # Show first 10
            print(f"   N={sol['N']}, ρ={sol['rho']:.8f}, δ={sol['delta_deg']:.1f}°")
            print(f"      Fractions: {sol['m1_n1']} and {sol['m2_n2']}")
    else:
        print(f"\n❌ No new solutions found in Phase 1 (N ≤ 120)")

    if higher_solutions:
        print(f"\n✨ HIGHER-N SOLUTIONS FOUND: {len(higher_solutions)}")
        for sol in higher_solutions:
            print(f"   N={sol['N']}, ρ={sol['rho']:.10f}, δ={np.degrees(sol['delta']):.0f}°")
            print(f"      Fractions: {sol['m1_n1']} and {sol['m2_n2']}")
    else:
        print(f"\n❌ No new solutions found in Phase 2 (N ≤ 240)")

    if not new_solutions and not higher_solutions:
        print("\n" + "💡 " * 20)
        print("CONCLUSION: Dukes' table for k=5 appears COMPLETE")
        print("The only solutions are ρ = (5 ± √5)/10 with N=60")
        print("This matches the paper's claim that only finite solutions exist")
        print("💡 " * 20)

    print("\n" + "=" * 80)