# -*- coding: utf-8 -*-
"""EXP024ad k12 none found search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YpkiGecpCKhSIr6AEpo3GxsLPyTV0O1u
"""

import numpy as np
from fractions import Fraction
from itertools import combinations
import warnings
warnings.filterwarnings('ignore')

def construct_U_k(k, rho, alpha, beta):
    """Construct quantum walk operator U_k on a cycle of k nodes."""
    C = np.array([
        [np.sqrt(rho), np.sqrt(1-rho) * np.exp(1j * alpha)],
        [np.sqrt(1-rho) * np.exp(1j * beta), -np.sqrt(rho) * np.exp(1j * (alpha + beta))]
    ], dtype=complex)

    U = np.zeros((2*k, 2*k), dtype=complex)

    for i in range(k):
        for s in [0, 1]:
            if s == 0:
                new_i = (i - 1) % k
            else:
                new_i = (i + 1) % k

            old_idx = i * 2 + s
            new_idx = new_i * 2 + s
            U[new_idx, old_idx] = 1.0

    I_k = np.eye(k)
    I_kron_C = np.kron(I_k, C)
    U = U @ I_kron_C

    return U

def verify_revival(k, rho, delta, N, tol=1e-8):
    """Verify that U_k^N = I_{2k}."""
    alpha = delta
    beta = 0.0

    U = construct_U_k(k, rho, alpha, beta)
    U_power = np.linalg.matrix_power(U, N)
    I = np.eye(2*k, dtype=complex)
    diff = np.linalg.norm(U_power - I)

    eigenvalues = np.linalg.eigvals(U)
    max_eig_error = max(abs(ev**N - 1) for ev in eigenvalues)

    return {
        'diff_norm': diff,
        'is_identity': diff < tol,
        'max_eig_error': max_eig_error
    }

def get_known_solutions_from_divisors():
    """
    Collect known solutions from divisors of 12: k=2,3,4,6
    Based on Dukes' tables.
    """
    print("\n" + "=" * 80)
    print("INHERITED SOLUTIONS FROM DIVISORS OF 12")
    print("=" * 80)

    # From k=3 solutions (Table 3)
    k3_solutions = [
        (8, 2/3, 0),
        (10, (5 - np.sqrt(5))/6, 0),
        (12, 1/3, 0),
        (12, 1/3, 2*np.pi/3),
        (12, 1/3, 4*np.pi/3),
        (14, 2/3 * (1 - np.cos(2*np.pi/7)), 0),
        (14, 2/3 * (1 - np.cos(4*np.pi/7)), 0),
        (16, (2 - np.sqrt(2))/3, 0),
        (18, 2/3 * (1 - np.cos(2*np.pi/9)), 0),
        (18, 2/3 * (1 - np.cos(4*np.pi/9)), 0),
        (20, (3 - np.sqrt(5))/6, 0),
        (20, (3 + np.sqrt(5))/6, 0),
        (24, (2 - np.sqrt(3))/3, 0),
        (24, 2/3, 2*np.pi/3),
        (24, 2/3, 4*np.pi/3),
        (30, (5 - np.sqrt(5))/6, 2*np.pi/3),
        (30, (5 - np.sqrt(5))/6, 4*np.pi/3),
    ]

    # From k=4 solutions (Table 4)
    k4_solutions = [
        (6, 3/4, 0),
        (8, 1/2, 0),
        (8, 1/2, np.pi),
        (12, 1/4, 0),
        (12, 1/4, np.pi),
        (12, 3/4, np.pi),
        (12, (2 - np.sqrt(3))/2, np.pi/2),
        (12, (2 - np.sqrt(3))/2, 3*np.pi/2),
        (16, (2 - np.sqrt(2))/4, 0),
        (16, (2 + np.sqrt(2))/4, 0),
        (20, (3 - np.sqrt(5))/8, 0),
        (20, (3 + np.sqrt(5))/8, 0),
        (24, (2 - np.sqrt(3))/4, 0),
        (24, (2 + np.sqrt(3))/4, 0),
        (24, 1/2, np.pi/2),
        (24, 1/2, 3*np.pi/2),
    ]

    # For k=12, we need to test which solutions actually work
    # due to the eigenvalue structure
    print("\nTesting k=3 solutions for k=12 (should work via doubling):")
    tested = []

    for N, rho, delta in k3_solutions:
        # Convert to float if needed
        if hasattr(rho, '__float__') or isinstance(rho, (int, float)):
            rho_val = float(rho)
        else:
            rho_val = rho

        result = verify_revival(12, rho_val, delta, N)
        if result['is_identity']:
            print(f"  ✓ N={N:2d}, ρ={rho_val:.8f}, δ={np.degrees(delta):.0f}°")
            tested.append((N, rho_val, delta))
        else:
            print(f"  ✗ N={N:2d}, ρ={rho_val:.8f} - Does NOT work for k=12")

    print("\nTesting k=4 solutions for k=12:")
    for N, rho, delta in k4_solutions:
        if hasattr(rho, '__float__') or isinstance(rho, (int, float)):
            rho_val = float(rho)
        else:
            rho_val = rho

        result = verify_revival(12, rho_val, delta, N)
        if result['is_identity']:
            print(f"  ✓ N={N:2d}, ρ={rho_val:.8f}, δ={np.degrees(delta):.0f}°")
            tested.append((N, rho_val, delta))
        else:
            print(f"  ✗ N={N:2d}, ρ={rho_val:.8f} - Does NOT work for k=12")

    return tested

def search_new_k12_revivals(max_denom=15, max_N=60):
    """
    Search for new k=12 revivals not inherited from divisors.

    For k=12, the paper's Eq. (78) becomes quite complex.
    We'll search systematically using the eigenvalue condition.
    """
    print("\n" + "=" * 80)
    print(f"SEARCHING FOR NEW k=12 REVIVALS (max_denom={max_denom}, max_N={max_N})")
    print("=" * 80)

    # Special δ values that simplify the equations for k=12
    # Since 12 is divisible by 2,3,4,6, many δ values might work
    delta_values = set()

    # From k=3: δ = 0, 2π/3, 4π/3
    delta_values.add(0)
    delta_values.add(2*np.pi/3)
    delta_values.add(4*np.pi/3)

    # From k=4: δ = 0, π/2, π, 3π/2
    delta_values.add(np.pi/2)
    delta_values.add(np.pi)
    delta_values.add(3*np.pi/2)

    # From k=6: should be same as k=3
    # From k=2: δ = 0 (already have)

    # Also try δ = 2π·p/12 for p coprime to 12
    for p in [1, 5, 7, 11]:  # coprime to 12
        delta_values.add(2*np.pi * p / 12)

    # Try δ = 2π·p/8? (since 12 and 8 share factors)
    for p in [1, 3, 5, 7]:
        delta_values.add(2*np.pi * p / 8)

    delta_list = sorted(list(delta_values))

    print(f"\nTesting {len(delta_list)} special δ values:")
    for delta in delta_list:
        print(f"  {np.degrees(delta):.0f}° ({delta:.4f} rad)")

    # Generate rational fractions for θ = 4π·m/n
    fractions = []
    for denom in range(1, max_denom + 1):
        for num in range(1, denom):
            if np.gcd(num, denom) == 1:
                fractions.append((num, denom, 4 * np.pi * num / denom))

    print(f"\nSearching through {len(fractions)} fractions...")

    new_solutions = []
    tested_pairs = 0

    # For k=12, the condition is that all ρ_l for l=0..11 are equal
    # This gives 11 independent equations

    for delta in delta_list:
        cos_delta = np.cos(delta)

        # We'll try to find consistent ρ from pairs of l values
        # l=0 and l=1 are typically most different

        for (num1, denom1, theta1) in fractions:
            # ρ from l=0 denominator: 1 - cos(δ)
            rho1 = (1 - np.cos(theta1 - delta)) / (1 - cos_delta) if abs(1 - cos_delta) > 1e-8 else 0

            if rho1 <= 0 or rho1 >= 1:
                continue

            # Now find matching fraction for l=1 denominator: 1 - cos(2π/12 + δ) = 1 - cos(π/6 + δ)
            target_for_l1 = rho1 * (1 - np.cos(np.pi/6 + delta))

            for (num2, denom2, theta2) in fractions:
                rho2_calc = 1 - np.cos(theta2 - delta)

                if abs(rho2_calc - target_for_l1) < 1e-6:
                    # Found a candidate pair
                    # Also need to check l=2,3,... but this is promising

                    # Estimate N from denominators
                    delta_frac = Fraction(delta / (2 * np.pi)).limit_denominator(max_denom * 2)
                    n_delta = delta_frac.denominator

                    N_candidate = np.lcm.reduce([denom1, denom2, n_delta * 2])

                    if N_candidate <= max_N:
                        result = verify_revival(12, rho1, delta, N_candidate)

                        if result['is_identity']:
                            # Check if this is already known
                            solution_key = (N_candidate, round(rho1, 8), round(delta, 4))

                            if solution_key not in new_solutions:
                                new_solutions.append({
                                    'N': N_candidate,
                                    'rho': rho1,
                                    'delta': delta,
                                    'delta_deg': np.degrees(delta),
                                    'frac1': f"{num1}/{denom1}",
                                    'frac2': f"{num2}/{denom2}",
                                    'delta_frac': delta_frac
                                })

                                print(f"\n✨ POTENTIAL NEW k=12 REVIVAL!")
                                print(f"   N = {N_candidate}")
                                print(f"   ρ = {rho1:.10f}")
                                print(f"   δ = {np.degrees(delta):.1f}° ({delta:.4f} rad)")
                                print(f"   δ/(2π) = {delta_frac}")
                                print(f"   Fractions: {num1}/{denom1}, {num2}/{denom2}")
                                print(f"   ||U^{N_candidate} - I|| = {result['diff_norm']:.2e}")

            tested_pairs += 1
            if tested_pairs % 1000 == 0:
                print(f"   Searched {tested_pairs} pairs, found {len(new_solutions)} candidates...")

    return new_solutions

def analyze_k12_eigenvalue_structure():
    """
    Analyze the theoretical constraints for k=12.
    """
    print("\n" + "=" * 80)
    print("THEORETICAL ANALYSIS FOR k=12")
    print("=" * 80)

    print("\nFor k=12, the eigenvalue blocks come from l = 0,1,...,11")
    print("\nThe denominators in ρ_l expressions are:")
    print("  l=0:  1 - cos(δ)")
    print("  l=1:  1 - cos(π/6 + δ)")
    print("  l=2:  1 - cos(π/3 + δ)")
    print("  l=3:  1 - cos(π/2 + δ) = 1 + sin(δ)")
    print("  l=4:  1 - cos(2π/3 + δ)")
    print("  l=5:  1 - cos(5π/6 + δ)")
    print("  l=6:  1 - cos(π + δ) = 1 + cos(δ)")
    print("  l=7:  1 - cos(7π/6 + δ) = 1 - cos(π/6 - δ)")
    print("  l=8:  1 - cos(4π/3 + δ)")
    print("  l=9:  1 - cos(3π/2 + δ) = 1 - sin(δ)")
    print("  l=10: 1 - cos(5π/3 + δ)")
    print("  l=11: 1 - cos(11π/6 + δ)")

    print("\nKey insight: Due to symmetries, many denominators are related.")
    print("The condition for revival is that all ρ_l are equal.")
    print("\nThis system is highly constrained. Solutions likely come from:")
    print("  1. Inherited from k=3 (δ = 0, 2π/3, 4π/3)")
    print("  2. Inherited from k=4 (δ = 0, π/2, π, 3π/2)")
    print("  3. Possibly new solutions unique to k=12")

def verify_inherited_with_higher_N():
    """
    Check if inherited solutions work with different N (maybe smaller due to degeneracy).
    """
    print("\n" + "=" * 80)
    print("CHECKING INHERITED SOLUTIONS WITH DIFFERENT N")
    print("=" * 80)

    # Test k=3 solutions with k=12
    test_cases = [
        (2/3, 0, [8, 16, 24, 32]),
        ((5 - np.sqrt(5))/6, 0, [10, 20, 30, 40]),
        (1/3, 0, [12, 24, 36]),
        (1/3, 2*np.pi/3, [12, 24, 36]),
        ((2 - np.sqrt(2))/3, 0, [16, 32, 48]),
    ]

    print("\nTesting k=3 solutions extended to k=12:")
    for rho, delta, N_list in test_cases:
        rho_val = float(rho) if hasattr(rho, '__float__') else rho
        for N in N_list:
            result = verify_revival(12, rho_val, delta, N)
            if result['is_identity']:
                print(f"  ✓ ρ={rho_val:.6f}, δ={np.degrees(delta):.0f}°, N={N:2d}")
                break
        else:
            print(f"  ✗ ρ={rho_val:.6f}, δ={np.degrees(delta):.0f}° - No revival up to N={N_list[-1]}")

# Main execution
if __name__ == "__main__":
    print("\n🔍 " * 30)
    print("INVESTIGATING k=12 QUANTUM STATE REVIVALS")
    print("🔍 " * 30)

    # Theoretical analysis
    analyze_k12_eigenvalue_structure()

    # Get inherited solutions from divisors
    inherited = get_known_solutions_from_divisors()

    # Check inherited with different N
    verify_inherited_with_higher_N()

    # Search for new solutions
    new_solutions = search_new_k12_revivals(max_denom=12, max_N=60)

    # Summary
    print("\n" + "=" * 80)
    print("FINAL SUMMARY FOR k=12")
    print("=" * 80)

    print(f"\n✓ Inherited solutions from divisors: {len(inherited)}")
    print("  These come from k=3 and k=4 solutions that survive the doubling")

    if new_solutions:
        nontrivial = [s for s in new_solutions if 0.01 < s['rho'] < 0.99]
        if nontrivial:
            print(f"\n✨ NEW NONTRIVIAL SOLUTIONS FOUND: {len(nontrivial)}")
            for sol in nontrivial[:10]:
                print(f"   N={sol['N']}, ρ={sol['rho']:.8f}, δ={sol['delta_deg']:.1f}°")
                print(f"      Fractions: {sol['frac1']}, {sol['frac2']}")
        else:
            print("\n📊 All new candidates are ρ=1 (trivial classical case)")
            print("   No new nontrivial (0<ρ<1) revivals found")
    else:
        print("\n📊 No new solutions found beyond inherited ones")

    print("\n💡 Key observation: k=12 inherits solutions from its divisors,")
    print("   but doesn't appear to have unique nontrivial revivals of its own.")
    print("   This supports Dukes' framework: revivals are determined by")
    print("   the prime factorization of k.")

    print("\n" + "=" * 80)