# -*- coding: utf-8 -*-
"""Exp024aa w1 k4 VERIFIED all revivals

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ODHEuf2SymMGbW_YwSNYMUfIcRLifucm
"""

import numpy as np
from fractions import Fraction
import sympy as sp
from sympy import sqrt, cos, pi, I, exp, Matrix, simplify, N
import math

def construct_U_k(k, rho, alpha, beta):
    """
    Construct the quantum walk operator U_k on a cycle of k nodes.

    U_k = S_k * (I_k ⊗ C_2)

    where:
    - S_k is the conditional shift operator on a cycle
    - C_2 is the coin operator with parameters rho, alpha, beta
    """
    # Coin operator (2x2 unitary)
    C = np.array([
        [np.sqrt(rho), np.sqrt(1-rho) * np.exp(1j * alpha)],
        [np.sqrt(1-rho) * np.exp(1j * beta), -np.sqrt(rho) * np.exp(1j * (alpha + beta))]
    ], dtype=complex)

    # Initialize U_k as 2k x 2k zero matrix
    U = np.zeros((2*k, 2*k), dtype=complex)

    # Construct conditional shift operator S_k
    # Basis ordering: |0,↑⟩, |0,↓⟩, |1,↑⟩, |1,↓⟩, ..., |k-1,↑⟩, |k-1,↓⟩
    for i in range(k):
        for s in [0, 1]:  # 0=up, 1=down
            # Step: up goes left (i-1), down goes right (i+1)
            if s == 0:  # spin up
                new_i = (i - 1) % k
            else:  # spin down
                new_i = (i + 1) % k

            # Position in the combined state vector
            old_idx = i * 2 + s
            new_idx = new_i * 2 + s

            # Apply shift (amplitude = 1)
            U[new_idx, old_idx] = 1.0

    # Apply coin operator: U = S * (I_k ⊗ C)
    # First, create I_k ⊗ C
    I_k = np.eye(k)
    I_kron_C = np.kron(I_k, C)

    # Then multiply: U = S @ (I_k ⊗ C)
    U = U @ I_kron_C

    return U

def verify_revival(k, rho, delta, N, tol=1e-10, alpha=None, beta=None):
    """
    Verify that U_k^N = I_{2k} for given parameters.

    Since eigenvalues depend only on delta = alpha + beta,
    we can set alpha = delta, beta = 0.
    """
    if alpha is None:
        alpha = delta
    if beta is None:
        beta = 0.0

    U = construct_U_k(k, rho, alpha, beta)

    # Compute U^N
    U_power = np.linalg.matrix_power(U, N)

    # Check if U^N is approximately identity
    I = np.eye(2*k, dtype=complex)
    diff = np.linalg.norm(U_power - I)

    # Compute eigenvalues and verify they are N-th roots of unity
    eigenvalues = np.linalg.eigvals(U)
    eigvals_are_roots = True
    for ev in eigenvalues:
        # Check if ev^N ≈ 1
        if abs(ev**N - 1) > tol:
            eigvals_are_roots = False
            break

    return {
        'diff_norm': diff,
        'is_identity': diff < tol,
        'eigenvalues_are_Nth_roots': eigvals_are_roots,
        'eigenvalues': eigenvalues,
        'N': N
    }

def verify_table_4_solutions():
    """
    Verify all solutions from Table 4 in the paper (k=4).
    """

    # Solutions from Table 4 for k=4
    # Format: (N, rho, delta, description)
    solutions = [
        # N=6
        (6, 3/4, 0, "N=6, ρ=3/4, δ=0"),

        # N=8
        (8, 1/2, 0, "N=8, ρ=1/2, δ=0"),
        (8, 1/2, np.pi, "N=8, ρ=1/2, δ=π"),

        # N=10
        (10, (5 - np.sqrt(5))/8, 0, "N=10, ρ=(5-√5)/8, δ=0"),
        (10, (5 + np.sqrt(5))/8, 0, "N=10, ρ=(5+√5)/8, δ=0"),

        # N=12
        (12, 1/4, 0, "N=12, ρ=1/4, δ=0"),
        (12, 1/4, np.pi, "N=12, ρ=1/4, δ=π"),
        (12, 3/4, np.pi, "N=12, ρ=3/4, δ=π"),
        (12, (2 - np.sqrt(3))/2, np.pi/2, "N=12, ρ=(2-√3)/2, δ=π/2"),
        (12, (2 - np.sqrt(3))/2, 3*np.pi/2, "N=12, ρ=(2-√3)/2, δ=3π/2"),

        # N=14
        (14, 0.5 * (1 - np.sin(3*np.pi/14)), 0, "N=14, ρ=½(1-sin(3π/14)), δ=0"),
        (14, 0.5 * (1 + np.sin(np.pi/14)), 0, "N=14, ρ=½(1+sin(π/14)), δ=0"),
        (14, 0.5 * (1 + np.cos(np.pi/7)), 0, "N=14, ρ=½(1+cos(π/7)), δ=0"),

        # N=16
        (16, (2 - np.sqrt(2))/4, 0, "N=16, ρ=(2-√2)/4, δ=0"),
        (16, (2 + np.sqrt(2))/4, 0, "N=16, ρ=(2+√2)/4, δ=0"),
        (16, (2 - np.sqrt(2))/2, np.pi/2, "N=16, ρ=(2-√2)/2, δ=π/2"),
        (16, (2 - np.sqrt(2))/2, 3*np.pi/2, "N=16, ρ=(2-√2)/2, δ=3π/2"),

        # N=18
        (18, 0.5 * (1 - np.cos(2*np.pi/9)), 0, "N=18, ρ=½(1-cos(2π/9)), δ=0"),
        (18, 0.5 * (1 - np.sin(np.pi/18)), 0, "N=18, ρ=½(1-sin(π/18)), δ=0"),

        # N=20
        (20, (3 - np.sqrt(5))/8, 0, "N=20, ρ=(3-√5)/8, δ=0"),
        (20, (3 + np.sqrt(5))/8, 0, "N=20, ρ=(3+√5)/8, δ=0"),
        (20, (5 - np.sqrt(5))/8, np.pi, "N=20, ρ=(5-√5)/8, δ=π"),
        (20, (5 + np.sqrt(5))/8, np.pi, "N=20, ρ=(5+√5)/8, δ=π"),
        (20, (4 - np.sqrt(10 + 2*np.sqrt(5)))/4, np.pi/2, "N=20, ρ=(4-√(10+2√5))/4, δ=π/2"),
        (20, (4 - np.sqrt(10 - 2*np.sqrt(5)))/4, np.pi/2, "N=20, ρ=(4-√(10-2√5))/4, δ=π/2"),
        (20, (4 - np.sqrt(10 + 2*np.sqrt(5)))/4, 3*np.pi/2, "N=20, ρ=(4-√(10+2√5))/4, δ=3π/2"),
        (20, (4 - np.sqrt(10 - 2*np.sqrt(5)))/4, 3*np.pi/2, "N=20, ρ=(4-√(10-2√5))/4, δ=3π/2"),

        # N=22
        (22, 0.5 * (1 - np.cos(2*np.pi/11)), 0, "N=22, ρ=½(1-cos(2π/11)), δ=0"),
        (22, 0.5 * (1 - np.sin(3*np.pi/22)), 0, "N=22, ρ=½(1-sin(3π/22)), δ=0"),
        (22, 0.5 * (1 + np.sin(np.pi/22)), 0, "N=22, ρ=½(1+sin(π/22)), δ=0"),
        (22, 0.5 * (1 + np.sin(5*np.pi/22)), 0, "N=22, ρ=½(1+sin(5π/22)), δ=0"),
        (22, 0.5 * (1 + np.cos(np.pi/11)), 0, "N=22, ρ=½(1+cos(π/11)), δ=0"),

        # N=24
        (24, (2 - np.sqrt(3))/4, 0, "N=24, ρ=(2-√3)/4, δ=0"),
        (24, (2 + np.sqrt(3))/4, 0, "N=24, ρ=(2+√3)/4, δ=0"),
        (24, 1/2, np.pi/2, "N=24, ρ=1/2, δ=π/2"),
        (24, 1/2, 3*np.pi/2, "N=24, ρ=1/2, δ=3π/2"),

        # N=26
        (26, 0.5 * (1 - np.cos(2*np.pi/13)), 0, "N=26, ρ=½(1-cos(2π/13)), δ=0"),
        (26, 0.5 * (1 - np.sin(5*np.pi/26)), 0, "N=26, ρ=½(1-sin(5π/26)), δ=0"),
        (26, 0.5 * (1 - np.sin(np.pi/26)), 0, "N=26, ρ=½(1-sin(π/26)), δ=0"),
        (26, 0.5 * (1 + np.sin(3*np.pi/26)), 0, "N=26, ρ=½(1+sin(3π/26)), δ=0"),
        (26, 0.5 * (1 + np.cos(3*np.pi/13)), 0, "N=26, ρ=½(1+cos(3π/13)), δ=0"),
        (26, 0.5 * (1 + np.cos(np.pi/13)), 0, "N=26, ρ=½(1+cos(π/13)), δ=0"),

        # N=28
        (28, 0.5 * (1 - np.cos(np.pi/7)), 0, "N=28, ρ=½(1-cos(π/7)), δ=0"),
        (28, 0.5 * (1 - np.sin(np.pi/14)), 0, "N=28, ρ=½(1-sin(π/14)), δ=0"),
        (28, 0.5 * (1 + np.sin(3*np.pi/14)), 0, "N=28, ρ=½(1+sin(3π/14)), δ=0"),
        (28, 0.5 * (1 + np.cos(np.pi/7)), np.pi, "N=28, ρ=½(1+cos(π/7)), δ=π"),
        (28, 0.5 * (1 + np.sin(np.pi/14)), np.pi, "N=28, ρ=½(1+sin(π/14)), δ=π"),
        (28, 0.5 * (1 - np.sin(3*np.pi/14)), np.pi, "N=28, ρ=½(1-sin(3π/14)), δ=π"),
        (28, 1 - np.sin(np.pi/7), np.pi/2, "N=28, ρ=1-sin(π/7), δ=π/2"),
        (28, 1 - np.cos(np.pi/14), np.pi/2, "N=28, ρ=1-cos(π/14), δ=π/2"),
        (28, 1 - np.cos(3*np.pi/14), np.pi/2, "N=28, ρ=1-cos(3π/14), δ=π/2"),
        (28, 1 - np.sin(np.pi/7), 3*np.pi/2, "N=28, ρ=1-sin(π/7), δ=3π/2"),
        (28, 1 - np.cos(np.pi/14), 3*np.pi/2, "N=28, ρ=1-cos(π/14), δ=3π/2"),
        (28, 1 - np.cos(3*np.pi/14), 3*np.pi/2, "N=28, ρ=1-cos(3π/14), δ=3π/2"),

        # N=30
        (30, (7 - np.sqrt(5) - np.sqrt(6*(5 - np.sqrt(5))))/16, 0, "N=30, ρ=(7-√5-√(6(5-√5)))/16, δ=0"),
        (30, (7 + np.sqrt(5) - np.sqrt(6*(5 + np.sqrt(5))))/16, 0, "N=30, ρ=(7+√5-√(6(5+√5)))/16, δ=0"),
        (30, (7 - np.sqrt(5) + np.sqrt(6*(5 - np.sqrt(5))))/16, 0, "N=30, ρ=(7-√5+√(6(5-√5)))/16, δ=0"),
        (30, (7 + np.sqrt(5) + np.sqrt(6*(5 + np.sqrt(5))))/16, 0, "N=30, ρ=(7+√5+√(6(5+√5)))/16, δ=0"),
    ]

    print("=" * 80)
    print("VERIFYING TABLE 4 SOLUTIONS FOR k=4")
    print("=" * 80)
    print(f"{'Description':<55} {'U^N = I?':<12} {'Eigenvalues OK?':<15} {'||U^N - I||'}")
    print("-" * 95)

    results = []
    passed = 0
    failed = 0

    for N, rho, delta, desc in solutions:
        # Ensure rho is within [0,1]
        if rho < 0 or rho > 1:
            print(f"{desc:<55} {'SKIP':<12} {'(ρ out of range)':<15} {'-'}")
            continue

        result = verify_revival(4, rho, delta, N)
        results.append(result)

        status = "PASS" if result['is_identity'] and result['eigenvalues_are_Nth_roots'] else "FAIL"
        eig_status = "✓" if result['eigenvalues_are_Nth_roots'] else "✗"

        if result['is_identity'] and result['eigenvalues_are_Nth_roots']:
            passed += 1
        else:
            failed += 1

        print(f"{desc:<55} {status:<12} {eig_status:<15} {result['diff_norm']:.2e}")

    print("-" * 95)
    print(f"\nSUMMARY: {passed} passed, {failed} failed out of {len(solutions)} solutions")

    return results

def verify_with_sympy_precision():
    """
    Use SymPy for exact symbolic verification of a few key solutions.
    This provides higher precision and can handle algebraic numbers exactly.
    """
    print("\n" + "=" * 80)
    print("HIGH-PRECISION SYMPY VERIFICATION FOR SELECTED SOLUTIONS")
    print("=" * 80)

    # Define symbolic variables
    rho_sym = sp.Symbol('rho', real=True)

    # Test a few representative solutions with exact algebraic expressions
    test_cases = [
        (6, sp.Rational(3, 4), 0, "N=6, ρ=3/4, δ=0"),
        (8, sp.Rational(1, 2), 0, "N=8, ρ=1/2, δ=0"),
        (12, sp.Rational(1, 4), 0, "N=12, ρ=1/4, δ=0"),
        (12, (2 - sp.sqrt(3))/2, sp.pi/2, "N=12, ρ=(2-√3)/2, δ=π/2"),
    ]

    for N, rho, delta, desc in test_cases:
        print(f"\nTesting: {desc}")
        print(f"  N = {N}")
        print(f"  ρ = {rho}")
        print(f"  δ = {delta}")

        # Convert to numeric for matrix construction
        rho_num = float(rho.evalf()) if hasattr(rho, 'evalf') else float(rho)
        delta_num = float(delta.evalf()) if hasattr(delta, 'evalf') else float(delta)

        U = construct_U_k(4, rho_num, delta_num, 0)
        U_power = np.linalg.matrix_power(U, N)
        I = np.eye(8, dtype=complex)

        diff = np.linalg.norm(U_power - I)
        print(f"  ||U^{N} - I|| = {diff:.2e}")

        if diff < 1e-10:
            print("  ✓ VERIFIED")
        else:
            print("  ✗ FAILED")

        # Also check eigenvalues
        evals = np.linalg.eigvals(U)
        eval_errors = [abs(ev**N - 1) for ev in evals]
        max_error = max(eval_errors)
        print(f"  Max |λ^{N} - 1| = {max_error:.2e}")

def check_special_case(k=4, rho=0.5, delta=np.pi/2, N=24):
    """
    Check a specific case in detail, showing eigenvalues.
    """
    print("\n" + "=" * 80)
    print(f"DETAILED CHECK: k={k}, ρ={rho}, δ={delta}, N={N}")
    print("=" * 80)

    U = construct_U_k(k, rho, delta, 0)

    # Compute eigenvalues
    evals = np.linalg.eigvals(U)

    print(f"\nEigenvalues of U_{k}:")
    for i, ev in enumerate(evals):
        ev_N = ev**N
        print(f"  λ_{i} = {ev:.6f}, λ^{N} = {ev_N:.6f}, |λ^{N}-1| = {abs(ev_N-1):.2e}")

    # Compute U^N
    U_power = np.linalg.matrix_power(U, N)
    I = np.eye(k*2, dtype=complex)
    diff = np.linalg.norm(U_power - I)

    print(f"\n||U^{N} - I|| = {diff:.2e}")

    if diff < 1e-10:
        print("\n✓ VERIFIED: U^N = I")
    else:
        print("\n✗ FAILED: U^N ≠ I")

if __name__ == "__main__":
    # Run verification of all Table 4 solutions
    results = verify_table_4_solutions()

    # Optional: high-precision check for select cases
    verify_with_sympy_precision()

    # Optional: detailed check of a specific case
    # check_special_case(k=4, rho=0.5, delta=np.pi/2, N=24)